import { useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

type Section = { name: string; icon: string; group: string; description: string; metric: string; action: string };
const sections: Section[] = [
  { name:'Dashboard',icon:'▦',group:'Overview',description:'Platform health, learning activity, and actions that need attention.',metric:'12,840 active learners',action:'Review platform health' },
  { name:'Users',icon:'◉',group:'People',description:'Search learners, manage account state, and review account activity.',metric:'1,284 total users',action:'Invite user' },
  { name:'Roles',icon:'♙',group:'People',description:'Define administrator roles and assign least-privilege access.',metric:'4 active roles',action:'Create role' },
  { name:'Permissions',icon:'⌘',group:'People',description:'Review capabilities granted to each administrative role.',metric:'28 permissions',action:'Review access' },
  { name:'Courses',icon:'▤',group:'Learning content',description:'Create and organize courses, units, completion rules, and certificates.',metric:'18 published courses',action:'Create course' },
  { name:'Lessons',icon:'☷',group:'Learning content',description:'Manage lesson flow, teaching material, and lesson status.',metric:'246 published lessons',action:'Create lesson' },
  { name:'Vocabulary',icon:'語',group:'Learning content',description:'Maintain shared vocabulary records and JLPT-alignment metadata.',metric:'1,126 course entries',action:'Add word' },
  { name:'Kanji',icon:'漢',group:'Learning content',description:'Maintain kanji readings, meanings, stroke data, and examples.',metric:'312 kanji records',action:'Add kanji' },
  { name:'Grammar',icon:'文',group:'Learning content',description:'Curate grammar patterns, examples, and learning relationships.',metric:'84 grammar patterns',action:'Add pattern' },
  { name:'Media',icon:'◫',group:'Learning content',description:'Manage audio, imagery, and other approved media assets.',metric:'64 approved assets',action:'Upload media' },
  { name:'Content Approval',icon:'✓',group:'Learning content',description:'Review drafts, provenance, and publishing decisions before release.',metric:'8 items awaiting review',action:'Open review queue' },
  { name:'AI',icon:'✦',group:'Intelligence',description:'Review AI drafts, safety configurations, and model activity.',metric:'14 drafts awaiting review',action:'Review AI drafts' },
  { name:'Reports',icon:'⚑',group:'Trust & safety',description:'Triage content and account reports with auditable decisions.',metric:'3 open reports',action:'Open reports' },
  { name:'Moderation',icon:'⛨',group:'Trust & safety',description:'Manage moderation actions, policies, and affected content.',metric:'0 urgent actions',action:'Moderation queue' },
  { name:'Audit Logs',icon:'◷',group:'Trust & safety',description:'Inspect administrative activity and security-relevant changes.',metric:'1,442 retained events',action:'View audit log' },
  { name:'Payments',icon:'₹',group:'Commerce',description:'Review verified transactions and provider reconciliation status.',metric:'₹84,520 this month',action:'View payments' },
  { name:'Coupons',icon:'◇',group:'Commerce',description:'Create, limit, and monitor promotional codes.',metric:'3 active coupons',action:'Create coupon' },
  { name:'Subscriptions',icon:'♛',group:'Commerce',description:'Manage subscription state and provider-verified entitlements.',metric:'182 active subscriptions',action:'View subscriptions' },
  { name:'Analytics',icon:'↗',group:'Operations',description:'Observe product usage and learning outcomes from real events.',metric:'71.4% weekly retention',action:'Open analytics' },
  { name:'Notifications',icon:'♧',group:'Operations',description:'Review notification templates, delivery health, and preferences.',metric:'98.7% in-app delivered',action:'Manage notifications' },
  { name:'System Settings',icon:'⚙',group:'Operations',description:'Configure environment-wide policies and service boundaries.',metric:'All systems operational',action:'Open system settings' },
];
const groupOrder = [...new Set(sections.map(s => s.group))];

function App() {
 const [selected,setSelected]=useState('Dashboard'); const [query,setQuery]=useState(''); const [compact,setCompact]=useState(false); const item=sections.find(s=>s.name===selected)!;
 const visible = sections.filter(s => s.name.toLowerCase().includes(query.toLowerCase()));
 return <div className={compact?'app compact':'app'}><aside className="sidebar"><div className="brand"><span>言</span><div><b>LangApp</b><small>ADMIN CONSOLE</small></div></div><label className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search console"/></label><nav>{groupOrder.map(group=>{const groupItems=visible.filter(s=>s.group===group);return groupItems.length?<section key={group}><p>{group}</p>{groupItems.map(s=><button className={s.name===selected?'active':''} key={s.name} onClick={()=>setSelected(s.name)}><i>{s.icon}</i><span>{s.name}</span>{s.name==='Content Approval'||s.name==='Reports'?<em>!</em>:null}</button>)}</section>:null})}</nav><div className="admin-user"><span>AK</span><div><b>Admin user</b><small>Administrator</small></div><button onClick={()=>setCompact(!compact)} aria-label="Toggle compact navigation">‹</button></div></aside><main><header className="topbar"><div><p>ADMINISTRATION / {item.group.toUpperCase()}</p><h1>{item.name}</h1></div><div className="top-actions"><button className="icon-btn">⌁</button><button className="icon-btn">♧<b>3</b></button><button className="profile">AK</button></div></header><section className="page-intro"><div><h2>{item.description}</h2><p>Connected administration surface. Data shown here should be served by authenticated, role-authorized API endpoints.</p></div><button className="primary">+ {item.action}</button></section>{selected==='Dashboard'?<Dashboard/>:<Management item={item}/>}</main></div>
}
function Dashboard(){const cards=[['Active learners','12,840','+12.6% vs last month'],['Learning events','48,291','Last 30 days'],['Reviews completed','93,502','86% retention'],['Revenue','₹84,520','Verified this month']];return <><section className="cards">{cards.map(c=><article key={c[0]}><span>{c[0]}</span><strong>{c[1]}</strong><small>{c[2]}</small></article>)}</section><section className="dashboard-grid"><article className="panel chart"><div className="panel-head"><div><p>LEARNING ACTIVITY</p><h3>Events over the last 7 days</h3></div><button>Last 7 days⌄</button></div><div className="bars">{[45,66,48,78,62,88,72].map((h,i)=><div key={i}><i style={{height:`${h}%`}}/><span>{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'][i]}</span></div>)}</div></article><article className="panel attention"><div className="panel-head"><div><p>NEEDS ATTENTION</p><h3>Review queues</h3></div></div><ul><li><span className="dot amber"/><div><b>Content approval</b><small>8 drafts are awaiting review</small></div><button>Open</button></li><li><span className="dot red"/><div><b>Reported content</b><small>3 reports need triage</small></div><button>Open</button></li><li><span className="dot blue"/><div><b>AI review</b><small>14 generated drafts awaiting review</small></div><button>Open</button></li></ul></article></section><section className="panel table"><div className="panel-head"><div><p>RECENT ADMIN ACTIVITY</p><h3>Auditable actions</h3></div><button>View all logs</button></div><div className="table-row heading"><span>Action</span><span>Actor</span><span>Area</span><span>When</span></div>{['Published “N4 Unit 3”','Approved grammar draft','Updated coupon limits','Reviewed reported content'].map((x,i)=><div className="table-row" key={x}><b>{x}</b><span>Admin user</span><span>{['Courses','AI','Coupons','Moderation'][i]}</span><time>{i+1}h ago</time></div>)}</section></>}
function Management({item}:{item:Section}){return <><section className="cards"><article><span>{item.name.toUpperCase()} STATUS</span><strong>{item.metric}</strong><small>Server-backed value required</small></article><article><span>ACCESS</span><strong>Role controlled</strong><small>Permissions are checked by the API</small></article><article><span>CHANGES</span><strong>Audited</strong><small>Administrative actions require an audit event</small></article></section><section className="panel management"><div className="panel-head"><div><p>{item.name.toUpperCase()} MANAGEMENT</p><h3>Records and operational controls</h3></div><div><button>Filter</button><button>Export</button></div></div><div className="empty"><span>{item.icon}</span><h3>Connect {item.name} to the Admin API</h3><p>This interface is ready for authorized data. Add the corresponding admin endpoint, server-side role check, audit event, and pagination before enabling live mutations.</p><button className="primary">{item.action}</button></div></section></>}
createRoot(document.getElementById('root')!).render(<App/>);
