import { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { login, request, type AdminSession, type ApiList } from './api';
import './styles.css';

type Section = { name:string; icon:string; group:string; endpoint?:string; description:string };
const sections:Section[]=[
{name:'Dashboard',icon:'▦',group:'Overview',endpoint:'/admin/stats',description:'Live platform health and operational queues.'},
{name:'Users',icon:'◉',group:'People',endpoint:'/admin/users?limit=25',description:'Search users and manage account state.'},{name:'Roles',icon:'♙',group:'People',endpoint:'/admin/roles',description:'Server-backed administrator roles.'},{name:'Permissions',icon:'⌘',group:'People',description:'Permission definitions are not yet exposed by the API.'},
{name:'Courses',icon:'▤',group:'Content',endpoint:'/admin/courses',description:'Course records from the content service.'},{name:'Lessons',icon:'☷',group:'Content',endpoint:'/admin/content/lessons/list?limit=25',description:'Lesson records from the content service.'},{name:'Vocabulary',icon:'語',group:'Content',endpoint:'/admin/content/vocab/list?limit=25',description:'Shared vocabulary records.'},{name:'Kanji',icon:'漢',group:'Content',endpoint:'/admin/content/kanji/list?limit=25',description:'Shared kanji records.'},{name:'Grammar',icon:'文',group:'Content',endpoint:'/admin/content/grammar/list?limit=25',description:'Shared grammar records.'},{name:'Media',icon:'◫',group:'Content',description:'Media catalog endpoint is not yet available.'},{name:'Content Approval',icon:'✓',group:'Content',description:'Approval queue endpoint is not yet available.'},
{name:'AI',icon:'✦',group:'Trust & safety',description:'AI review endpoint is not yet available.'},{name:'Reports',icon:'⚑',group:'Trust & safety',endpoint:'/admin/reports/content',description:'Content reports requiring moderation.'},{name:'Moderation',icon:'⛨',group:'Trust & safety',endpoint:'/admin/reports/users',description:'Community reports requiring moderation.'},{name:'Audit Logs',icon:'◷',group:'Trust & safety',endpoint:'/admin/audit-logs?limit=25',description:'Privileged actions recorded by the API.'},
{name:'Payments',icon:'₹',group:'Commerce',description:'Payments administration endpoint is not yet available.'},{name:'Coupons',icon:'◇',group:'Commerce',endpoint:'/admin/coupons',description:'Server-backed coupon records.'},{name:'Subscriptions',icon:'♛',group:'Commerce',description:'Subscription administration endpoint is not yet available.'},
{name:'Analytics',icon:'↗',group:'Operations',endpoint:'/admin/analytics',description:'Live account segmentation metrics.'},{name:'Notifications',icon:'♧',group:'Operations',endpoint:'/admin/notifications',description:'Notification administration.'},{name:'System Settings',icon:'⚙',group:'Operations',endpoint:'/admin/settings',description:'Environment-wide settings protected by admin authorization.'}];
const groups=[...new Set(sections.map(s=>s.group))]; const key='langapp-admin-session';
function App(){const [session,setSession]=useState<AdminSession|null>(()=>{try{return JSON.parse(localStorage.getItem(key)||'null')}catch{return null}});return session?<Console session={session} logout={()=>{localStorage.removeItem(key);setSession(null)}}/>:<Login onSession={s=>{localStorage.setItem(key,JSON.stringify(s));setSession(s)}}/>}
function Login({onSession}:{onSession:(s:AdminSession)=>void}){const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[error,setError]=useState('');const[busy,setBusy]=useState(false);return <div className="login"><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{onSession(await login(email,password))}catch(err){setError(err instanceof Error?err.message:'Login failed')}finally{setBusy(false)}}}><div className="login-mark">言</div><p>LANGAPP ADMINISTRATION</p><h1>Sign in securely</h1><span>Use an account that has the server-side administrator role.</span><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{error&&<div className="error">{error}</div>}<button className="primary" disabled={busy}>{busy?'Signing in…':'Sign in to Admin'}</button><small>API URL: {import.meta.env.VITE_API_URL || 'same origin (/v1)'}</small></form></div>}
function Console({session,logout}:{session:AdminSession;logout:()=>void}){const[selected,setSelected]=useState('Dashboard');const[query,setQuery]=useState('');const item=sections.find(x=>x.name===selected)!;const visible=sections.filter(x=>x.name.toLowerCase().includes(query.toLowerCase()));return <div className="app"><aside className="sidebar"><div className="brand"><span>言</span><div><b>LangApp</b><small>ADMIN CONSOLE</small></div></div><label className="search">⌕<input placeholder="Search console" value={query} onChange={e=>setQuery(e.target.value)}/></label><nav>{groups.map(g=>{const rows=visible.filter(x=>x.group===g);return rows.length?<section key={g}><p>{g}</p>{rows.map(x=><button className={x.name===selected?'active':''} onClick={()=>setSelected(x.name)} key={x.name}><i>{x.icon}</i><span>{x.name}</span></button>)}</section>:null})}</nav><div className="admin-user"><span>{session.user.profile.displayName.slice(0,2).toUpperCase()}</span><div><b>{session.user.profile.displayName}</b><small>Administrator</small></div><button onClick={logout}>⇥</button></div></aside><main><header className="topbar"><div><p>ADMINISTRATION / {item.group.toUpperCase()}</p><h1>{item.name}</h1></div><div className="top-actions"><span className="live"><i/> API connected</span><button className="profile">{session.user.profile.displayName.slice(0,2).toUpperCase()}</button></div></header><section className="page-intro"><div><h2>{item.description}</h2><p>Every request uses the signed-in bearer token; the API remains the authority for admin access and mutations.</p></div></section>{item.name==='Dashboard'?<Dashboard token={session.accessToken}/>:<Resource item={item} token={session.accessToken}/>}</main></div>}
function useData<T>(path:string|undefined,token:string){const[data,setData]=useState<T|null>(null);const[error,setError]=useState('');const[loading,setLoading]=useState(!!path);useEffect(()=>{let active=true;if(!path){setLoading(false);return}setLoading(true);setError('');request<T>(path,token).then(x=>active&&setData(x)).catch(e=>active&&setError(e.message)).finally(()=>active&&setLoading(false));return()=>{active=false}},[path,token]);return{data,error,loading}}
function Dashboard({token}:{token:string}){const stats=useData<{totalUsers:number;activeToday:number;pendingContentReports:number;pendingUserReports:number}>('/admin/stats',token);const counts=useData<Record<string,number>>('/admin/content/counts',token);const analytics=useData<{totalUsers:number;proUsers:number;freeUsers:number}>('/admin/analytics',token);if(stats.loading||counts.loading)return <Loading/>;if(stats.error)return <Failure text={stats.error}/>;const rows=[['Total learners',stats.data?.totalUsers],['Active today',stats.data?.activeToday],['Vocabulary',counts.data?.vocab],['Lessons',counts.data?.lessons],['Courses',counts.data?.courses],['Pro users',analytics.data?.proUsers]];return <><section className="cards">{rows.map(([a,b])=><article key={String(a)}><span>{a}</span><strong>{b??'—'}</strong><small>Live API value</small></article>)}</section><section className="dashboard-grid"><article className="panel"><div className="panel-head"><div><p>OPEN QUEUES</p><h3>Moderation attention</h3></div></div><ul className="queue"><li><b>Content reports</b><span>{stats.data?.pendingContentReports??0} open</span></li><li><b>Community reports</b><span>{stats.data?.pendingUserReports??0} open</span></li></ul></article><article className="panel"><p>ENTITLEMENT SNAPSHOT</p><h3>{analytics.data?.proUsers??0} paid accounts</h3><small>{analytics.data?.freeUsers??0} free accounts · derived by the API</small></article></section></>}
function Resource({item,token}:{item:Section;token:string}){const{data,error,loading}=useData<unknown>(item.endpoint,token);if(!item.endpoint)return <section className="panel empty"><span>{item.icon}</span><h3>Backend contract required</h3><p>{item.description} Build a protected admin endpoint, role check, validation and audit event before this control is enabled.</p></section>;if(loading)return <Loading/>;if(error)return <Failure text={error}/>;const payload=data as ApiList<Record<string,unknown>>|Record<string,unknown>;const list='items'in payload&&Array.isArray(payload.items)?payload.items:null;return <section className="panel resource"><div className="panel-head"><div><p>LIVE API RESPONSE</p><h3>{list?`${payload.total??list.length} records`:'Current settings'}</h3></div><button onClick={()=>navigator.clipboard.writeText(JSON.stringify(data,null,2))}>Copy JSON</button></div>{list?<div className="records">{list.length===0?<p>No records returned.</p>:list.map((row,i)=><article key={String(row.id??row._id??i)}><b>{String(row.displayName??row.lemma??row.char??row.title??row.code??row.action??row.email??'Record')}</b><span>{Object.entries(row).filter(([k])=>!['_id','id'].includes(k)).slice(0,4).map(([k,v])=>`${k}: ${Array.isArray(v)?v.join(', '):String(v)}`).join(' · ')}</span></article>)}</div>:<pre>{JSON.stringify(data,null,2)}</pre>}</section>}
function Loading(){return <section className="panel state">Loading live data…</section>}function Failure({text}:{text:string}){return <section className="panel state error"><b>Request failed</b><p>{text}</p><small>Confirm VITE_API_URL, CORS_ORIGINS, the API service, and this account's isAdmin flag.</small></section>}
createRoot(document.getElementById('root')!).render(<App/>);
