import { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { login, request, type AdminSession, type ApiList } from './api';
import './styles.css';

type Tool={name:string;icon:string;endpoint?:string;create?:string;description:string};
const tools:Tool[]=[
{name:'Course Builder',icon:'▤',endpoint:'/admin/courses',create:'/admin/courses',description:'Compose courses, sequencing, completion rules, and certificates.'},{name:'Lesson Builder',icon:'☷',endpoint:'/admin/content/lessons/list?limit=30',create:'/admin/content/lessons',description:'Author structured lessons using shared learning items.'},{name:'Quiz Builder',icon:'?',endpoint:'/admin/quizzes?limit=30',create:'/admin/quizzes',description:'Build question sets using the shared assessment engine.'},{name:'Kanji Editor',icon:'漢',endpoint:'/admin/content/kanji/list?limit=30',create:'/admin/content/kanji',description:'Create kanji entries with readings and curriculum metadata.'},{name:'Vocabulary Editor',icon:'語',endpoint:'/admin/content/vocab/list?limit=30',create:'/admin/content/vocab',description:'Create vocabulary entries aligned to the shared corpus.'},{name:'Grammar Editor',icon:'文',endpoint:'/admin/content/grammar/list?limit=30',create:'/admin/content/grammar',description:'Maintain grammar patterns, examples, and level alignment.'},{name:'Audio Manager',icon:'◖',description:'Upload and manage approved audio assets.'},{name:'Media Library',icon:'◫',description:'Browse approved media, attribution, and usage metadata.'},{name:'Drafts',icon:'◌',description:'Draft workflow endpoint is required before this view can be enabled.'},{name:'Publishing',icon:'↑',description:'Publishing workflow endpoint is required before this view can be enabled.'},{name:'Version History',icon:'◷',description:'Select an individual content record to inspect API-backed versions.'}];
const key='langapp-creator-session';
function App(){const[s,setS]=useState<AdminSession|null>(()=>{try{return JSON.parse(localStorage.getItem(key)||'null')}catch{return null}});return s?<CMS session={s} logout={()=>{localStorage.removeItem(key);setS(null)}}/>:<Login ready={x=>{localStorage.setItem(key,JSON.stringify(x));setS(x)}}/>}
function Login({ready}:{ready:(s:AdminSession)=>void}){const[email,setEmail]=useState('');const[pw,setPw]=useState('');const[error,setError]=useState('');return <div className="login"><form onSubmit={async e=>{e.preventDefault();try{ready(await login(email,pw))}catch(x){setError(x instanceof Error?x.message:'Unable to sign in')}}}><div className="login-mark">文</div><p>LANGAPP CREATOR</p><h1>Author securely</h1><span>Sign in with an authorized content administrator account.</span><label>Email<input value={email} onChange={e=>setEmail(e.target.value)} type="email" required/></label><label>Password<input value={pw} onChange={e=>setPw(e.target.value)} type="password" required/></label>{error&&<div className="error">{error}</div>}<button className="primary">Sign in to CMS</button></form></div>}
function CMS({session,logout}:{session:AdminSession;logout:()=>void}){const[active,setActive]=useState(tools[0]);return <div className="app"><aside className="sidebar"><div className="brand"><span>文</span><div><b>LangApp</b><small>CREATOR / CMS</small></div></div><nav>{tools.map(t=><section key={t.name}><button className={active.name===t.name?'active':''} onClick={()=>setActive(t)}><i>{t.icon}</i><span>{t.name}</span></button></section>)}</nav><div className="admin-user"><span>{session.user.profile.displayName.slice(0,2)}</span><div><b>{session.user.profile.displayName}</b><small>Content administrator</small></div><button onClick={logout}>⇥</button></div></aside><main><header className="topbar"><div><p>CREATOR / CONTENT STUDIO</p><h1>{active.name}</h1></div><div className="top-actions"><span className="live"><i/> Authenticated API</span></div></header><section className="page-intro"><div><h2>{active.description}</h2><p>Content saves and destructive actions must be validated and audited by the server.</p></div></section><Workspace tool={active} token={session.accessToken}/></main></div>}
function Workspace({tool,token}:{tool:Tool;token:string}){const[data,setData]=useState<ApiList<Record<string,unknown>>|null>(null);const[error,setError]=useState('');const[loading,setLoading]=useState(!!tool.endpoint);const[form,setForm]=useState('');const[notice,setNotice]=useState('');useEffect(()=>{if(!tool.endpoint){setData(null);setLoading(false);return}let ok=true;setLoading(true);setError('');request<ApiList<Record<string,unknown>>>(tool.endpoint,token).then(x=>ok&&setData(x)).catch(e=>ok&&setError(e.message)).finally(()=>ok&&setLoading(false));return()=>{ok=false}},[tool,token]);if(!tool.endpoint)return <section className="panel empty"><span>{tool.icon}</span><h3>Workflow contract required</h3><p>{tool.description} This workspace is deliberately unavailable until its server endpoint includes draft state, review/publish rules, validation, and audit logging.</p></section>;const create=async()=>{try{const body=JSON.parse(form);await request(tool.create!,token,{method:'POST',body:JSON.stringify(body)});setForm('');setNotice('Saved. Reload this workspace to view the server record.')}catch(e){setNotice(e instanceof Error?e.message:'Could not save')}};return <div className="creator-grid"><section className="panel resource"><div className="panel-head"><div><p>LIVE CONTENT</p><h3>{loading?'Loading…':`${data?.total??0} records`}</h3></div></div>{error?<div className="error">{error}</div>:<div className="records">{data?.items.map((x,i)=><article key={String(x.id??i)}><b>{String(x.title??x.lemma??x.char??x.name??'Untitled')}</b><span>{Object.entries(x).filter(([k])=>!['id','_id'].includes(k)).slice(0,4).map(([k,v])=>`${k}: ${Array.isArray(v)?v.join(', '):String(v)}`).join(' · ')}</span></article>)}</div>}</section><section className="panel creator-form"><p>SERVER-VALIDATED CREATE</p><h3>New {tool.name.replace(' Builder','').replace(' Editor','')}</h3><span>Paste a JSON payload matching the API schema. The backend validates, persists, and audits the write.</span><textarea value={form} onChange={e=>setForm(e.target.value)} placeholder={'{\n  "title": "…"\n}'}/>{notice&&<div className="error">{notice}</div>}<button className="primary" onClick={create} disabled={!form.trim()}>Create with API</button></section></div>}
createRoot(document.getElementById('root')!).render(<App/>);
