import type { VocabSeed, VocabLessonSeed } from './vocab';

/**
 * The third vocabulary unit — 512 words, the ones that finish JLPT N5.
 *
 * ## Why this exists and how big it had to be
 *
 * N5 is conventionally about **800 words and 100 kanji**. The kanji side was
 * already there (`kanji-basics`, 104), but the vocabulary was not: 58 in
 * `vocab-basics`, 12 in the marks-words units and 220 in `vocab-everyday` is
 * 290 — roughly a third of the level. This unit closes that gap, taking the
 * course to **802 words**.
 *
 * ## The constraints, unchanged from `vocab-everyday`
 *
 * Only characters the kana units teach; **no small vowels (ぁぃぅぇぉ / ァィゥェォ)
 * or ヴ**, since no unit introduces them; no っ before ち, where the
 * transliterator's doubling rule and Hepburn disagree; `reading` identical to
 * `lemma`; and **no lemma any earlier unit already owns**, because `lemma` is
 * the key `upsertVocab` writes on and a collision silently rewrites the older
 * word's gloss rather than adding a new one.
 *
 * All four are enforced by `vocab-n5.spec.ts`, and every romaji here is checked
 * against the mechanical transliterator in `romaji.spec.ts`.
 *
 * ## Words deliberately absent
 *
 * こんばんは and こんばんわ-style greetings ending in the topic particle are not
 * here: は read as `wa` needs a listed exception in the romaji spec, and one
 * such exception (こんにちは) is enough to make the point without turning the
 * exception list into a second vocabulary. The same goes for anything needing
 * フォ, ティ or ヴ — フォーク and パーティー look like beginner words and are
 * unspellable with what the course teaches.
 */
export const VOCAB_N5_GROUPS: Record<string, VocabSeed[]> = {
  fruit: [
    { lemma: 'りんご', reading: 'りんご', romaji: 'ringo', gloss: 'apple', pos: 'noun' },
    { lemma: 'みかん', reading: 'みかん', romaji: 'mikan', gloss: 'mandarin orange', pos: 'noun' },
    { lemma: 'いちご', reading: 'いちご', romaji: 'ichigo', gloss: 'strawberry', pos: 'noun' },
    { lemma: 'ぶどう', reading: 'ぶどう', romaji: 'budou', gloss: 'grapes', pos: 'noun' },
    { lemma: 'もも', reading: 'もも', romaji: 'momo', gloss: 'peach', pos: 'noun' },
    { lemma: 'なし', reading: 'なし', romaji: 'nashi', gloss: 'pear', pos: 'noun' },
    { lemma: 'すいか', reading: 'すいか', romaji: 'suika', gloss: 'watermelon', pos: 'noun' },
    { lemma: 'バナナ', reading: 'バナナ', romaji: 'banana', gloss: 'banana', pos: 'noun' },
    { lemma: 'メロン', reading: 'メロン', romaji: 'meron', gloss: 'melon', pos: 'noun' },
    { lemma: 'レモン', reading: 'レモン', romaji: 'remon', gloss: 'lemon', pos: 'noun' },
    { lemma: 'かき', reading: 'かき', romaji: 'kaki', gloss: 'persimmon', pos: 'noun' },
    { lemma: 'くり', reading: 'くり', romaji: 'kuri', gloss: 'chestnut', pos: 'noun' },
  ],
  vegetables: [
    { lemma: 'にんじん', reading: 'にんじん', romaji: 'ninjin', gloss: 'carrot', pos: 'noun' },
    { lemma: 'たまねぎ', reading: 'たまねぎ', romaji: 'tamanegi', gloss: 'onion', pos: 'noun' },
    { lemma: 'じゃがいも', reading: 'じゃがいも', romaji: 'jagaimo', gloss: 'potato', pos: 'noun' },
    { lemma: 'きゅうり', reading: 'きゅうり', romaji: 'kyuuri', gloss: 'cucumber', pos: 'noun' },
    { lemma: 'トマト', reading: 'トマト', romaji: 'tomato', gloss: 'tomato', pos: 'noun' },
    { lemma: 'キャベツ', reading: 'キャベツ', romaji: 'kyabetsu', gloss: 'cabbage', pos: 'noun' },
    { lemma: 'だいこん', reading: 'だいこん', romaji: 'daikon', gloss: 'daikon radish', pos: 'noun' },
    { lemma: 'なす', reading: 'なす', romaji: 'nasu', gloss: 'aubergine', pos: 'noun' },
    { lemma: 'ねぎ', reading: 'ねぎ', romaji: 'negi', gloss: 'spring onion', pos: 'noun' },
    { lemma: 'まめ', reading: 'まめ', romaji: 'mame', gloss: 'bean', pos: 'noun' },
    { lemma: 'きのこ', reading: 'きのこ', romaji: 'kinoko', gloss: 'mushroom', pos: 'noun' },
    { lemma: 'ごま', reading: 'ごま', romaji: 'goma', gloss: 'sesame', pos: 'noun' },
  ],
  dishes: [
    { lemma: 'りょうり', reading: 'りょうり', romaji: 'ryouri', gloss: 'cooking, a dish', pos: 'noun' },
    { lemma: 'すし', reading: 'すし', romaji: 'sushi', gloss: 'sushi', pos: 'noun' },
    { lemma: 'てんぷら', reading: 'てんぷら', romaji: 'tenpura', gloss: 'tempura', pos: 'noun' },
    { lemma: 'そば', reading: 'そば', romaji: 'soba', gloss: 'buckwheat noodles', pos: 'noun' },
    { lemma: 'うどん', reading: 'うどん', romaji: 'udon', gloss: 'udon noodles', pos: 'noun' },
    { lemma: 'ラーメン', reading: 'ラーメン', romaji: 'raamen', gloss: 'ramen', pos: 'noun' },
    { lemma: 'カレー', reading: 'カレー', romaji: 'karee', gloss: 'curry', pos: 'noun' },
    { lemma: 'サラダ', reading: 'サラダ', romaji: 'sarada', gloss: 'salad', pos: 'noun' },
    { lemma: 'ハンバーガー', reading: 'ハンバーガー', romaji: 'hanbaagaa', gloss: 'hamburger', pos: 'noun' },
    { lemma: 'おべんとう', reading: 'おべんとう', romaji: 'obentou', gloss: 'packed lunch', pos: 'noun' },
    { lemma: 'あじ', reading: 'あじ', romaji: 'aji', gloss: 'taste, flavour', pos: 'noun' },
    { lemma: 'しお', reading: 'しお', romaji: 'shio', gloss: 'salt', pos: 'noun' },
    { lemma: 'さとう', reading: 'さとう', romaji: 'satou', gloss: 'sugar', pos: 'noun' },
    { lemma: 'あぶら', reading: 'あぶら', romaji: 'abura', gloss: 'oil', pos: 'noun' },
  ],
  kitchen: [
    { lemma: 'なべ', reading: 'なべ', romaji: 'nabe', gloss: 'a pot', pos: 'noun' },
    { lemma: 'さら', reading: 'さら', romaji: 'sara', gloss: 'a plate', pos: 'noun' },
    { lemma: 'コップ', reading: 'コップ', romaji: 'koppu', gloss: 'a glass', pos: 'noun' },
    { lemma: 'おはし', reading: 'おはし', romaji: 'ohashi', gloss: 'chopsticks', pos: 'noun' },
    { lemma: 'スプーン', reading: 'スプーン', romaji: 'supuun', gloss: 'a spoon', pos: 'noun' },
    { lemma: 'ナイフ', reading: 'ナイフ', romaji: 'naifu', gloss: 'a knife', pos: 'noun' },
    { lemma: 'やく', reading: 'やく', romaji: 'yaku', gloss: 'to grill, to bake', pos: 'verb' },
    { lemma: 'にる', reading: 'にる', romaji: 'niru', gloss: 'to simmer', pos: 'verb' },
    { lemma: 'きる', reading: 'きる', romaji: 'kiru', gloss: 'to cut', pos: 'verb' },
    { lemma: 'まぜる', reading: 'まぜる', romaji: 'mazeru', gloss: 'to mix', pos: 'verb' },
    { lemma: 'わかす', reading: 'わかす', romaji: 'wakasu', gloss: 'to boil water', pos: 'verb' },
    { lemma: 'ゆ', reading: 'ゆ', romaji: 'yu', gloss: 'hot water', pos: 'noun' },
    { lemma: 'こおり', reading: 'こおり', romaji: 'koori', gloss: 'ice', pos: 'noun' },
  ],
  animals: [
    { lemma: 'いぬ', reading: 'いぬ', romaji: 'inu', gloss: 'dog', pos: 'noun' },
    { lemma: 'ねこ', reading: 'ねこ', romaji: 'neko', gloss: 'cat', pos: 'noun' },
    { lemma: 'とり', reading: 'とり', romaji: 'tori', gloss: 'bird', pos: 'noun' },
    { lemma: 'うま', reading: 'うま', romaji: 'uma', gloss: 'horse', pos: 'noun' },
    { lemma: 'うし', reading: 'うし', romaji: 'ushi', gloss: 'cow', pos: 'noun' },
    { lemma: 'ぶた', reading: 'ぶた', romaji: 'buta', gloss: 'pig', pos: 'noun' },
    { lemma: 'ひつじ', reading: 'ひつじ', romaji: 'hitsuji', gloss: 'sheep', pos: 'noun' },
    { lemma: 'さる', reading: 'さる', romaji: 'saru', gloss: 'monkey', pos: 'noun' },
    { lemma: 'くま', reading: 'くま', romaji: 'kuma', gloss: 'bear', pos: 'noun' },
    { lemma: 'きつね', reading: 'きつね', romaji: 'kitsune', gloss: 'fox', pos: 'noun' },
    { lemma: 'むし', reading: 'むし', romaji: 'mushi', gloss: 'insect', pos: 'noun' },
    { lemma: 'へび', reading: 'へび', romaji: 'hebi', gloss: 'snake', pos: 'noun' },
    { lemma: 'かめ', reading: 'かめ', romaji: 'kame', gloss: 'turtle', pos: 'noun' },
    { lemma: 'ねずみ', reading: 'ねずみ', romaji: 'nezumi', gloss: 'mouse', pos: 'noun' },
    { lemma: 'とら', reading: 'とら', romaji: 'tora', gloss: 'tiger', pos: 'noun' },
    { lemma: 'ぞう', reading: 'ぞう', romaji: 'zou', gloss: 'elephant', pos: 'noun' },
    { lemma: 'しか', reading: 'しか', romaji: 'shika', gloss: 'deer', pos: 'noun' },
    { lemma: 'こねこ', reading: 'こねこ', romaji: 'koneko', gloss: 'kitten', pos: 'noun' },
  ],
  nature: [
    { lemma: 'き', reading: 'き', romaji: 'ki', gloss: 'a tree', pos: 'noun' },
    { lemma: 'もり', reading: 'もり', romaji: 'mori', gloss: 'a forest', pos: 'noun' },
    { lemma: 'かわ', reading: 'かわ', romaji: 'kawa', gloss: 'a river', pos: 'noun' },
    { lemma: 'いけ', reading: 'いけ', romaji: 'ike', gloss: 'a pond', pos: 'noun' },
    { lemma: 'みずうみ', reading: 'みずうみ', romaji: 'mizuumi', gloss: 'a lake', pos: 'noun' },
    { lemma: 'しま', reading: 'しま', romaji: 'shima', gloss: 'an island', pos: 'noun' },
    { lemma: 'いし', reading: 'いし', romaji: 'ishi', gloss: 'a stone', pos: 'noun' },
    { lemma: 'すな', reading: 'すな', romaji: 'suna', gloss: 'sand', pos: 'noun' },
    { lemma: 'つち', reading: 'つち', romaji: 'tsuchi', gloss: 'soil', pos: 'noun' },
    { lemma: 'くさ', reading: 'くさ', romaji: 'kusa', gloss: 'grass', pos: 'noun' },
    { lemma: 'は', reading: 'は', romaji: 'ha', gloss: 'a leaf', pos: 'noun' },
    { lemma: 'たね', reading: 'たね', romaji: 'tane', gloss: 'a seed', pos: 'noun' },
    { lemma: 'くも', reading: 'くも', romaji: 'kumo', gloss: 'a cloud', pos: 'noun' },
    { lemma: 'ひかり', reading: 'ひかり', romaji: 'hikari', gloss: 'light', pos: 'noun' },
    { lemma: 'かげ', reading: 'かげ', romaji: 'kage', gloss: 'a shadow', pos: 'noun' },
    { lemma: 'おと', reading: 'おと', romaji: 'oto', gloss: 'a sound', pos: 'noun' },
  ],
  body: [
    { lemma: 'かみのけ', reading: 'かみのけ', romaji: 'kaminoke', gloss: 'hair', pos: 'noun' },
    { lemma: 'ゆび', reading: 'ゆび', romaji: 'yubi', gloss: 'a finger', pos: 'noun' },
    { lemma: 'つめ', reading: 'つめ', romaji: 'tsume', gloss: 'a nail', pos: 'noun' },
    { lemma: 'ひざ', reading: 'ひざ', romaji: 'hiza', gloss: 'a knee', pos: 'noun' },
    { lemma: 'うで', reading: 'うで', romaji: 'ude', gloss: 'an arm', pos: 'noun' },
    { lemma: 'かた', reading: 'かた', romaji: 'kata', gloss: 'a shoulder', pos: 'noun' },
    { lemma: 'むね', reading: 'むね', romaji: 'mune', gloss: 'a chest', pos: 'noun' },
    { lemma: 'こし', reading: 'こし', romaji: 'koshi', gloss: 'the lower back', pos: 'noun' },
    { lemma: 'ち', reading: 'ち', romaji: 'chi', gloss: 'blood', pos: 'noun' },
    { lemma: 'ほね', reading: 'ほね', romaji: 'hone', gloss: 'a bone', pos: 'noun' },
    { lemma: 'こえ', reading: 'こえ', romaji: 'koe', gloss: 'a voice', pos: 'noun' },
    { lemma: 'なみだ', reading: 'なみだ', romaji: 'namida', gloss: 'a tear', pos: 'noun' },
    { lemma: 'いき', reading: 'いき', romaji: 'iki', gloss: 'a breath', pos: 'noun' },
    { lemma: 'はだ', reading: 'はだ', romaji: 'hada', gloss: 'skin', pos: 'noun' },
  ],
  health: [
    { lemma: 'ねつ', reading: 'ねつ', romaji: 'netsu', gloss: 'a fever', pos: 'noun' },
    { lemma: 'せき', reading: 'せき', romaji: 'seki', gloss: 'a cough', pos: 'noun' },
    { lemma: 'けが', reading: 'けが', romaji: 'kega', gloss: 'an injury', pos: 'noun' },
    { lemma: 'いたい', reading: 'いたい', romaji: 'itai', gloss: 'painful', pos: 'adjective' },
    { lemma: 'つかれる', reading: 'つかれる', romaji: 'tsukareru', gloss: 'to get tired', pos: 'verb' },
    { lemma: 'なおる', reading: 'なおる', romaji: 'naoru', gloss: 'to get better', pos: 'verb' },
    { lemma: 'やすむ', reading: 'やすむ', romaji: 'yasumu', gloss: 'to rest, to take a day off', pos: 'verb' },
    { lemma: 'ねむい', reading: 'ねむい', romaji: 'nemui', gloss: 'sleepy', pos: 'adjective' },
    { lemma: 'びょうにん', reading: 'びょうにん', romaji: 'byounin', gloss: 'a sick person', pos: 'noun' },
    { lemma: 'はいしゃ', reading: 'はいしゃ', romaji: 'haisha', gloss: 'a dentist', pos: 'noun' },
    { lemma: 'くすりや', reading: 'くすりや', romaji: 'kusuriya', gloss: 'a pharmacy', pos: 'noun' },
    { lemma: 'たいおん', reading: 'たいおん', romaji: 'taion', gloss: 'body temperature', pos: 'noun' },
    { lemma: 'しんぱい', reading: 'しんぱい', romaji: 'shinpai', gloss: 'worry', pos: 'noun' },
    { lemma: 'あんぜん', reading: 'あんぜん', romaji: 'anzen', gloss: 'safety', pos: 'noun' },
  ],
  family: [
    { lemma: 'そふ', reading: 'そふ', romaji: 'sofu', gloss: 'my grandfather', pos: 'noun' },
    { lemma: 'そぼ', reading: 'そぼ', romaji: 'sobo', gloss: 'my grandmother', pos: 'noun' },
    { lemma: 'おじ', reading: 'おじ', romaji: 'oji', gloss: 'uncle', pos: 'noun' },
    { lemma: 'おば', reading: 'おば', romaji: 'oba', gloss: 'aunt', pos: 'noun' },
    { lemma: 'いとこ', reading: 'いとこ', romaji: 'itoko', gloss: 'cousin', pos: 'noun' },
    { lemma: 'まご', reading: 'まご', romaji: 'mago', gloss: 'grandchild', pos: 'noun' },
    { lemma: 'つま', reading: 'つま', romaji: 'tsuma', gloss: 'my wife', pos: 'noun' },
    { lemma: 'おっと', reading: 'おっと', romaji: 'otto', gloss: 'my husband', pos: 'noun' },
    { lemma: 'むすこ', reading: 'むすこ', romaji: 'musuko', gloss: 'son', pos: 'noun' },
    { lemma: 'むすめ', reading: 'むすめ', romaji: 'musume', gloss: 'daughter', pos: 'noun' },
    { lemma: 'きょうだい', reading: 'きょうだい', romaji: 'kyoudai', gloss: 'siblings', pos: 'noun' },
    { lemma: 'しんせき', reading: 'しんせき', romaji: 'shinseki', gloss: 'a relative', pos: 'noun' },
    { lemma: 'りょうしん', reading: 'りょうしん', romaji: 'ryoushin', gloss: 'parents', pos: 'noun' },
    { lemma: 'ぼく', reading: 'ぼく', romaji: 'boku', gloss: 'I (casual, male)', pos: 'pronoun' },
  ],
  feelings: [
    { lemma: 'うれしい', reading: 'うれしい', romaji: 'ureshii', gloss: 'glad', pos: 'adjective' },
    { lemma: 'かなしい', reading: 'かなしい', romaji: 'kanashii', gloss: 'sad', pos: 'adjective' },
    { lemma: 'さびしい', reading: 'さびしい', romaji: 'sabishii', gloss: 'lonely', pos: 'adjective' },
    { lemma: 'こわい', reading: 'こわい', romaji: 'kowai', gloss: 'frightening', pos: 'adjective' },
    { lemma: 'はずかしい', reading: 'はずかしい', romaji: 'hazukashii', gloss: 'embarrassing', pos: 'adjective' },
    { lemma: 'うらやましい', reading: 'うらやましい', romaji: 'urayamashii', gloss: 'enviable', pos: 'adjective' },
    { lemma: 'しあわせ', reading: 'しあわせ', romaji: 'shiawase', gloss: 'happiness', pos: 'noun' },
    { lemma: 'きもち', reading: 'きもち', romaji: 'kimochi', gloss: 'a feeling', pos: 'noun' },
    { lemma: 'あんしん', reading: 'あんしん', romaji: 'anshin', gloss: 'relief', pos: 'noun' },
    { lemma: 'おこる', reading: 'おこる', romaji: 'okoru', gloss: 'to get angry', pos: 'verb' },
    { lemma: 'なく', reading: 'なく', romaji: 'naku', gloss: 'to cry', pos: 'verb' },
    { lemma: 'わらう', reading: 'わらう', romaji: 'warau', gloss: 'to laugh', pos: 'verb' },
    { lemma: 'おどろく', reading: 'おどろく', romaji: 'odoroku', gloss: 'to be surprised', pos: 'verb' },
    { lemma: 'こまる', reading: 'こまる', romaji: 'komaru', gloss: 'to be troubled', pos: 'verb' },
    { lemma: 'たのむ', reading: 'たのむ', romaji: 'tanomu', gloss: 'to request', pos: 'verb' },
    { lemma: 'よろこぶ', reading: 'よろこぶ', romaji: 'yorokobu', gloss: 'to rejoice', pos: 'verb' },
    { lemma: 'すき', reading: 'すき', romaji: 'suki', gloss: 'liked', pos: 'adjective' },
    { lemma: 'きらい', reading: 'きらい', romaji: 'kirai', gloss: 'disliked', pos: 'adjective' },
  ],
  character: [
    { lemma: 'やさしい', reading: 'やさしい', romaji: 'yasashii', gloss: 'kind, gentle', pos: 'adjective' },
    { lemma: 'きびしい', reading: 'きびしい', romaji: 'kibishii', gloss: 'strict', pos: 'adjective' },
    { lemma: 'まじめ', reading: 'まじめ', romaji: 'majime', gloss: 'serious, diligent', pos: 'adjective' },
    { lemma: 'しんせつ', reading: 'しんせつ', romaji: 'shinsetsu', gloss: 'helpful', pos: 'adjective' },
    { lemma: 'へた', reading: 'へた', romaji: 'heta', gloss: 'unskilful', pos: 'adjective' },
    { lemma: 'じょうず', reading: 'じょうず', romaji: 'jouzu', gloss: 'skilful', pos: 'adjective' },
    { lemma: 'ゆうめいじん', reading: 'ゆうめいじん', romaji: 'yuumeijin', gloss: 'a celebrity', pos: 'noun' },
    { lemma: 'せいかく', reading: 'せいかく', romaji: 'seikaku', gloss: 'personality', pos: 'noun' },
    { lemma: 'わかい', reading: 'わかい', romaji: 'wakai', gloss: 'young', pos: 'adjective' },
    { lemma: 'つよさ', reading: 'つよさ', romaji: 'tsuyosa', gloss: 'strength', pos: 'noun' },
    { lemma: 'えらい', reading: 'えらい', romaji: 'erai', gloss: 'admirable', pos: 'adjective' },
    { lemma: 'ひま', reading: 'ひま', romaji: 'hima', gloss: 'free time', pos: 'noun' },
    { lemma: 'いそがしい', reading: 'いそがしい', romaji: 'isogashii', gloss: 'busy', pos: 'adjective' },
    { lemma: 'げんきん', reading: 'げんきん', romaji: 'genkin', gloss: 'cash', pos: 'noun' },
  ],
  colours: [
    { lemma: 'いろ', reading: 'いろ', romaji: 'iro', gloss: 'a colour', pos: 'noun' },
    { lemma: 'あか', reading: 'あか', romaji: 'aka', gloss: 'red', pos: 'noun' },
    { lemma: 'あお', reading: 'あお', romaji: 'ao', gloss: 'blue', pos: 'noun' },
    { lemma: 'しろ', reading: 'しろ', romaji: 'shiro', gloss: 'white', pos: 'noun' },
    { lemma: 'くろ', reading: 'くろ', romaji: 'kuro', gloss: 'black', pos: 'noun' },
    { lemma: 'きいろ', reading: 'きいろ', romaji: 'kiiro', gloss: 'yellow', pos: 'noun' },
    { lemma: 'みどり', reading: 'みどり', romaji: 'midori', gloss: 'green', pos: 'noun' },
    { lemma: 'ちゃいろ', reading: 'ちゃいろ', romaji: 'chairo', gloss: 'brown', pos: 'noun' },
    { lemma: 'むらさき', reading: 'むらさき', romaji: 'murasaki', gloss: 'purple', pos: 'noun' },
    { lemma: 'はいいろ', reading: 'はいいろ', romaji: 'haiiro', gloss: 'grey', pos: 'noun' },
    { lemma: 'あかい', reading: 'あかい', romaji: 'akai', gloss: 'red (adjective)', pos: 'adjective' },
    { lemma: 'あおい', reading: 'あおい', romaji: 'aoi', gloss: 'blue (adjective)', pos: 'adjective' },
  ],
  house: [
    { lemma: 'げんかん', reading: 'げんかん', romaji: 'genkan', gloss: 'an entrance hall', pos: 'noun' },
    { lemma: 'ろうか', reading: 'ろうか', romaji: 'rouka', gloss: 'a corridor', pos: 'noun' },
    { lemma: 'てんじょう', reading: 'てんじょう', romaji: 'tenjou', gloss: 'a ceiling', pos: 'noun' },
    { lemma: 'やね', reading: 'やね', romaji: 'yane', gloss: 'a roof', pos: 'noun' },
    { lemma: 'もん', reading: 'もん', romaji: 'mon', gloss: 'a gate', pos: 'noun' },
    { lemma: 'かぐ', reading: 'かぐ', romaji: 'kagu', gloss: 'furniture', pos: 'noun' },
    { lemma: 'たな', reading: 'たな', romaji: 'tana', gloss: 'a shelf', pos: 'noun' },
    { lemma: 'ひきだし', reading: 'ひきだし', romaji: 'hikidashi', gloss: 'a drawer', pos: 'noun' },
    { lemma: 'ふとん', reading: 'ふとん', romaji: 'futon', gloss: 'a futon', pos: 'noun' },
    { lemma: 'まくら', reading: 'まくら', romaji: 'makura', gloss: 'a pillow', pos: 'noun' },
    { lemma: 'カーテン', reading: 'カーテン', romaji: 'kaaten', gloss: 'a curtain', pos: 'noun' },
    { lemma: 'じゅうたん', reading: 'じゅうたん', romaji: 'juutan', gloss: 'a carpet', pos: 'noun' },
    { lemma: 'でぐち', reading: 'でぐち', romaji: 'deguchi', gloss: 'an exit', pos: 'noun' },
    { lemma: 'いりぐち', reading: 'いりぐち', romaji: 'iriguchi', gloss: 'an entrance', pos: 'noun' },
    { lemma: 'かがみ', reading: 'かがみ', romaji: 'kagami', gloss: 'a mirror', pos: 'noun' },
    { lemma: 'タオル', reading: 'タオル', romaji: 'taoru', gloss: 'a towel', pos: 'noun' },
    { lemma: 'せっけん', reading: 'せっけん', romaji: 'sekken', gloss: 'soap', pos: 'noun' },
    { lemma: 'ごみ', reading: 'ごみ', romaji: 'gomi', gloss: 'rubbish', pos: 'noun' },
  ],
  objects: [
    { lemma: 'テレビ', reading: 'テレビ', romaji: 'terebi', gloss: 'a television', pos: 'noun' },
    { lemma: 'ラジオ', reading: 'ラジオ', romaji: 'rajio', gloss: 'a radio', pos: 'noun' },
    { lemma: 'カメラ', reading: 'カメラ', romaji: 'kamera', gloss: 'a camera', pos: 'noun' },
    { lemma: 'とけいや', reading: 'とけいや', romaji: 'tokeiya', gloss: 'a watchmaker', pos: 'noun' },
    { lemma: 'でんち', reading: 'でんち', romaji: 'denchi', gloss: 'a battery', pos: 'noun' },
    { lemma: 'はこ', reading: 'はこ', romaji: 'hako', gloss: 'a box', pos: 'noun' },
    { lemma: 'ふくろ', reading: 'ふくろ', romaji: 'fukuro', gloss: 'a bag, a sack', pos: 'noun' },
    { lemma: 'かびん', reading: 'かびん', romaji: 'kabin', gloss: 'a vase', pos: 'noun' },
    { lemma: 'ひも', reading: 'ひも', romaji: 'himo', gloss: 'a string', pos: 'noun' },
    { lemma: 'はり', reading: 'はり', romaji: 'hari', gloss: 'a needle', pos: 'noun' },
    { lemma: 'いと', reading: 'いと', romaji: 'ito', gloss: 'thread', pos: 'noun' },
    { lemma: 'ぬの', reading: 'ぬの', romaji: 'nuno', gloss: 'cloth', pos: 'noun' },
    { lemma: 'シャワー', reading: 'シャワー', romaji: 'shawaa', gloss: 'a shower', pos: 'noun' },
    { lemma: 'ストーブ', reading: 'ストーブ', romaji: 'sutoobu', gloss: 'a heater', pos: 'noun' },
    { lemma: 'エアコン', reading: 'エアコン', romaji: 'eakon', gloss: 'an air conditioner', pos: 'noun' },
    { lemma: 'けしゴム', reading: 'けしゴム', romaji: 'keshigomu', gloss: 'an eraser', pos: 'noun' },
    { lemma: 'ものさし', reading: 'ものさし', romaji: 'monosashi', gloss: 'a ruler', pos: 'noun' },
  ],
  clothes: [
    { lemma: 'きもの', reading: 'きもの', romaji: 'kimono', gloss: 'a kimono', pos: 'noun' },
    { lemma: 'うわぎ', reading: 'うわぎ', romaji: 'uwagi', gloss: 'a jacket', pos: 'noun' },
    { lemma: 'したぎ', reading: 'したぎ', romaji: 'shitagi', gloss: 'underwear', pos: 'noun' },
    { lemma: 'ぼたん', reading: 'ぼたん', romaji: 'botan', gloss: 'a button', pos: 'noun' },
    { lemma: 'ポケット', reading: 'ポケット', romaji: 'poketto', gloss: 'a pocket', pos: 'noun' },
    { lemma: 'サイズ', reading: 'サイズ', romaji: 'saizu', gloss: 'a size', pos: 'noun' },
    { lemma: 'はく', reading: 'はく', romaji: 'haku', gloss: 'to wear (below the waist)', pos: 'verb' },
    { lemma: 'かぶる', reading: 'かぶる', romaji: 'kaburu', gloss: 'to wear on the head', pos: 'verb' },
    { lemma: 'ぬぐ', reading: 'ぬぐ', romaji: 'nugu', gloss: 'to take off', pos: 'verb' },
    { lemma: 'にあう', reading: 'にあう', romaji: 'niau', gloss: 'to suit', pos: 'verb' },
    { lemma: 'よごれる', reading: 'よごれる', romaji: 'yogoreru', gloss: 'to get dirty', pos: 'verb' },
    { lemma: 'ゆかた', reading: 'ゆかた', romaji: 'yukata', gloss: 'a summer kimono', pos: 'noun' },
    { lemma: 'くつや', reading: 'くつや', romaji: 'kutsuya', gloss: 'a shoe shop', pos: 'noun' },
  ],
  town: [
    { lemma: 'こうじょう', reading: 'こうじょう', romaji: 'koujou', gloss: 'a factory', pos: 'noun' },
    { lemma: 'じんじゃ', reading: 'じんじゃ', romaji: 'jinja', gloss: 'a shrine', pos: 'noun' },
    { lemma: 'おてら', reading: 'おてら', romaji: 'otera', gloss: 'a temple', pos: 'noun' },
    { lemma: 'こうさてん', reading: 'こうさてん', romaji: 'kousaten', gloss: 'a crossroads', pos: 'noun' },
    { lemma: 'しんごう', reading: 'しんごう', romaji: 'shingou', gloss: 'a traffic light', pos: 'noun' },
    { lemma: 'ちゅうしゃじょう', reading: 'ちゅうしゃじょう', romaji: 'chuushajou', gloss: 'a car park', pos: 'noun' },
    { lemma: 'やおや', reading: 'やおや', romaji: 'yaoya', gloss: 'a greengrocer', pos: 'noun' },
    { lemma: 'にくや', reading: 'にくや', romaji: 'nikuya', gloss: 'a butcher', pos: 'noun' },
    { lemma: 'ほんや', reading: 'ほんや', romaji: 'honya', gloss: 'a bookshop', pos: 'noun' },
    { lemma: 'はなや', reading: 'はなや', romaji: 'hanaya', gloss: 'a florist', pos: 'noun' },
    { lemma: 'パンや', reading: 'パンや', romaji: 'panya', gloss: 'a bakery', pos: 'noun' },
    { lemma: 'ちず', reading: 'ちず', romaji: 'chizu', gloss: 'a map', pos: 'noun' },
    { lemma: 'ばしょ', reading: 'ばしょ', romaji: 'basho', gloss: 'a place', pos: 'noun' },
    { lemma: 'となり', reading: 'となり', romaji: 'tonari', gloss: 'next door', pos: 'noun' },
    { lemma: 'ちかく', reading: 'ちかく', romaji: 'chikaku', gloss: 'nearby', pos: 'noun' },
    { lemma: 'とおく', reading: 'とおく', romaji: 'tooku', gloss: 'far away', pos: 'noun' },
    { lemma: 'かど', reading: 'かど', romaji: 'kado', gloss: 'a corner', pos: 'noun' },
    { lemma: 'むこう', reading: 'むこう', romaji: 'mukou', gloss: 'the other side', pos: 'noun' },
  ],
  transport: [
    { lemma: 'こうつう', reading: 'こうつう', romaji: 'koutsuu', gloss: 'traffic', pos: 'noun' },
    { lemma: 'しんかんせん', reading: 'しんかんせん', romaji: 'shinkansen', gloss: 'the bullet train', pos: 'noun' },
    { lemma: 'バスてい', reading: 'バスてい', romaji: 'basutei', gloss: 'a bus stop', pos: 'noun' },
    { lemma: 'ホーム', reading: 'ホーム', romaji: 'hoomu', gloss: 'a platform', pos: 'noun' },
    { lemma: 'うんてん', reading: 'うんてん', romaji: 'unten', gloss: 'driving', pos: 'noun' },
    { lemma: 'じこ', reading: 'じこ', romaji: 'jiko', gloss: 'an accident', pos: 'noun' },
    { lemma: 'みぎ', reading: 'みぎ', romaji: 'migi', gloss: 'right', pos: 'noun' },
    { lemma: 'ひだり', reading: 'ひだり', romaji: 'hidari', gloss: 'left', pos: 'noun' },
    { lemma: 'まっすぐ', reading: 'まっすぐ', romaji: 'massugu', gloss: 'straight ahead', pos: 'adverb' },
    { lemma: 'きた', reading: 'きた', romaji: 'kita', gloss: 'north', pos: 'noun' },
    { lemma: 'みなみ', reading: 'みなみ', romaji: 'minami', gloss: 'south', pos: 'noun' },
    { lemma: 'ひがし', reading: 'ひがし', romaji: 'higashi', gloss: 'east', pos: 'noun' },
    { lemma: 'にし', reading: 'にし', romaji: 'nishi', gloss: 'west', pos: 'noun' },
    { lemma: 'うえ', reading: 'うえ', romaji: 'ue', gloss: 'above', pos: 'noun' },
    { lemma: 'した', reading: 'した', romaji: 'shita', gloss: 'below', pos: 'noun' },
    { lemma: 'なか', reading: 'なか', romaji: 'naka', gloss: 'inside', pos: 'noun' },
  ],
  travel: [
    { lemma: 'やど', reading: 'やど', romaji: 'yado', gloss: 'lodging', pos: 'noun' },
    { lemma: 'よやく', reading: 'よやく', romaji: 'yoyaku', gloss: 'a reservation', pos: 'noun' },
    { lemma: 'パスポート', reading: 'パスポート', romaji: 'pasupooto', gloss: 'a passport', pos: 'noun' },
    { lemma: 'にもつ', reading: 'にもつ', romaji: 'nimotsu', gloss: 'luggage', pos: 'noun' },
    { lemma: 'スーツケース', reading: 'スーツケース', romaji: 'suutsukeesu', gloss: 'a suitcase', pos: 'noun' },
    { lemma: 'おみやげ', reading: 'おみやげ', romaji: 'omiyage', gloss: 'a souvenir', pos: 'noun' },
    { lemma: 'しゃしん', reading: 'しゃしん', romaji: 'shashin', gloss: 'a photograph', pos: 'noun' },
    { lemma: 'けしき', reading: 'けしき', romaji: 'keshiki', gloss: 'scenery', pos: 'noun' },
    { lemma: 'がいこく', reading: 'がいこく', romaji: 'gaikoku', gloss: 'a foreign country', pos: 'noun' },
    { lemma: 'がいこくじん', reading: 'がいこくじん', romaji: 'gaikokujin', gloss: 'a foreigner', pos: 'noun' },
    { lemma: 'せかい', reading: 'せかい', romaji: 'sekai', gloss: 'the world', pos: 'noun' },
    { lemma: 'ちきゅう', reading: 'ちきゅう', romaji: 'chikyuu', gloss: 'the Earth', pos: 'noun' },
    { lemma: 'でかける', reading: 'でかける', romaji: 'dekakeru', gloss: 'to go out', pos: 'verb' },
    { lemma: 'つく', reading: 'つく', romaji: 'tsuku', gloss: 'to arrive', pos: 'verb' },
    { lemma: 'とおる', reading: 'とおる', romaji: 'tooru', gloss: 'to pass through', pos: 'verb' },
    { lemma: 'わたる', reading: 'わたる', romaji: 'wataru', gloss: 'to cross', pos: 'verb' },
  ],
  school: [
    { lemma: 'だいがくせい', reading: 'だいがくせい', romaji: 'daigakusei', gloss: 'a university student', pos: 'noun' },
    { lemma: 'こうこう', reading: 'こうこう', romaji: 'koukou', gloss: 'high school', pos: 'noun' },
    { lemma: 'しょうがっこう', reading: 'しょうがっこう', romaji: 'shougakkou', gloss: 'primary school', pos: 'noun' },
    { lemma: 'にゅうがく', reading: 'にゅうがく', romaji: 'nyuugaku', gloss: 'entering a school', pos: 'noun' },
    { lemma: 'そつぎょう', reading: 'そつぎょう', romaji: 'sotsugyou', gloss: 'graduation', pos: 'noun' },
    { lemma: 'がっき', reading: 'がっき', romaji: 'gakki', gloss: 'a school term', pos: 'noun' },
    { lemma: 'なつやすみ', reading: 'なつやすみ', romaji: 'natsuyasumi', gloss: 'the summer holiday', pos: 'noun' },
    { lemma: 'しけん', reading: 'しけん', romaji: 'shiken', gloss: 'an examination', pos: 'noun' },
    { lemma: 'せいせき', reading: 'せいせき', romaji: 'seiseki', gloss: 'a grade, a result', pos: 'noun' },
    { lemma: 'さくぶん', reading: 'さくぶん', romaji: 'sakubun', gloss: 'an essay', pos: 'noun' },
    { lemma: 'ぶんぽう', reading: 'ぶんぽう', romaji: 'bunpou', gloss: 'grammar', pos: 'noun' },
    { lemma: 'たんご', reading: 'たんご', romaji: 'tango', gloss: 'a word, vocabulary', pos: 'noun' },
    { lemma: 'はつおん', reading: 'はつおん', romaji: 'hatsuon', gloss: 'pronunciation', pos: 'noun' },
    { lemma: 'いみ', reading: 'いみ', romaji: 'imi', gloss: 'a meaning', pos: 'noun' },
    { lemma: 'れんしゅう', reading: 'れんしゅう', romaji: 'renshuu', gloss: 'practice', pos: 'noun' },
    { lemma: 'ふくしゅう', reading: 'ふくしゅう', romaji: 'fukushuu', gloss: 'revision', pos: 'noun' },
    { lemma: 'しゅうかん', reading: 'しゅうかん', romaji: 'shuukan', gloss: 'a habit', pos: 'noun' },
    { lemma: 'きょうかしょ', reading: 'きょうかしょ', romaji: 'kyoukasho', gloss: 'a textbook', pos: 'noun' },
  ],
  work: [
    { lemma: 'やくしょ', reading: 'やくしょ', romaji: 'yakusho', gloss: 'a government office', pos: 'noun' },
    { lemma: 'しゃいん', reading: 'しゃいん', romaji: 'shain', gloss: 'a staff member', pos: 'noun' },
    { lemma: 'ぶちょう', reading: 'ぶちょう', romaji: 'buchou', gloss: 'a department head', pos: 'noun' },
    { lemma: 'けいけん', reading: 'けいけん', romaji: 'keiken', gloss: 'experience', pos: 'noun' },
    { lemma: 'もくてき', reading: 'もくてき', romaji: 'mokuteki', gloss: 'a purpose', pos: 'noun' },
    { lemma: 'けいかく', reading: 'けいかく', romaji: 'keikaku', gloss: 'a plan', pos: 'noun' },
    { lemma: 'じゅんび', reading: 'じゅんび', romaji: 'junbi', gloss: 'preparation', pos: 'noun' },
    { lemma: 'ほうこく', reading: 'ほうこく', romaji: 'houkoku', gloss: 'a report', pos: 'noun' },
    { lemma: 'しょるい', reading: 'しょるい', romaji: 'shorui', gloss: 'documents', pos: 'noun' },
    { lemma: 'はんこ', reading: 'はんこ', romaji: 'hanko', gloss: 'a personal seal', pos: 'noun' },
    { lemma: 'つとめる', reading: 'つとめる', romaji: 'tsutomeru', gloss: 'to be employed', pos: 'verb' },
    { lemma: 'やめる', reading: 'やめる', romaji: 'yameru', gloss: 'to quit', pos: 'verb' },
    { lemma: 'きめる', reading: 'きめる', romaji: 'kimeru', gloss: 'to decide', pos: 'verb' },
    { lemma: 'しらべる', reading: 'しらべる', romaji: 'shiraberu', gloss: 'to look into', pos: 'verb' },
    { lemma: 'てつだう', reading: 'てつだう', romaji: 'tetsudau', gloss: 'to help', pos: 'verb' },
    { lemma: 'あつまる', reading: 'あつまる', romaji: 'atsumaru', gloss: 'to gather', pos: 'verb' },
  ],
  money: [
    { lemma: 'かいもの', reading: 'かいもの', romaji: 'kaimono', gloss: 'shopping', pos: 'noun' },
    { lemma: 'レジ', reading: 'レジ', romaji: 'reji', gloss: 'a checkout', pos: 'noun' },
    { lemma: 'おつり', reading: 'おつり', romaji: 'otsuri', gloss: 'change', pos: 'noun' },
    { lemma: 'りょうしゅうしょ', reading: 'りょうしゅうしょ', romaji: 'ryoushuusho', gloss: 'a receipt', pos: 'noun' },
    { lemma: 'わりびき', reading: 'わりびき', romaji: 'waribiki', gloss: 'a discount', pos: 'noun' },
    { lemma: 'むりょう', reading: 'むりょう', romaji: 'muryou', gloss: 'free of charge', pos: 'noun' },
    { lemma: 'ぜいきん', reading: 'ぜいきん', romaji: 'zeikin', gloss: 'tax', pos: 'noun' },
    { lemma: 'ぎんこういん', reading: 'ぎんこういん', romaji: 'ginkouin', gloss: 'a bank clerk', pos: 'noun' },
    { lemma: 'こうざ', reading: 'こうざ', romaji: 'kouza', gloss: 'a bank account', pos: 'noun' },
    { lemma: 'はらう', reading: 'はらう', romaji: 'harau', gloss: 'to pay', pos: 'verb' },
    { lemma: 'かりる', reading: 'かりる', romaji: 'kariru', gloss: 'to borrow', pos: 'verb' },
    { lemma: 'かえす', reading: 'かえす', romaji: 'kaesu', gloss: 'to give back', pos: 'verb' },
    { lemma: 'ためる', reading: 'ためる', romaji: 'tameru', gloss: 'to save up', pos: 'verb' },
    { lemma: 'たかさ', reading: 'たかさ', romaji: 'takasa', gloss: 'height', pos: 'noun' },
  ],
  days: [
    { lemma: 'げつようび', reading: 'げつようび', romaji: 'getsuyoubi', gloss: 'Monday', pos: 'noun' },
    { lemma: 'かようび', reading: 'かようび', romaji: 'kayoubi', gloss: 'Tuesday', pos: 'noun' },
    { lemma: 'すいようび', reading: 'すいようび', romaji: 'suiyoubi', gloss: 'Wednesday', pos: 'noun' },
    { lemma: 'もくようび', reading: 'もくようび', romaji: 'mokuyoubi', gloss: 'Thursday', pos: 'noun' },
    { lemma: 'きんようび', reading: 'きんようび', romaji: 'kinyoubi', gloss: 'Friday', pos: 'noun' },
    { lemma: 'どようび', reading: 'どようび', romaji: 'doyoubi', gloss: 'Saturday', pos: 'noun' },
    { lemma: 'にちようび', reading: 'にちようび', romaji: 'nichiyoubi', gloss: 'Sunday', pos: 'noun' },
    { lemma: 'へいじつ', reading: 'へいじつ', romaji: 'heijitsu', gloss: 'a weekday', pos: 'noun' },
    { lemma: 'きょねん', reading: 'きょねん', romaji: 'kyonen', gloss: 'last year', pos: 'noun' },
    { lemma: 'らいねん', reading: 'らいねん', romaji: 'rainen', gloss: 'next year', pos: 'noun' },
    { lemma: 'ことし', reading: 'ことし', romaji: 'kotoshi', gloss: 'this year', pos: 'noun' },
    { lemma: 'せんしゅう', reading: 'せんしゅう', romaji: 'senshuu', gloss: 'last week', pos: 'noun' },
    { lemma: 'らいしゅう', reading: 'らいしゅう', romaji: 'raishuu', gloss: 'next week', pos: 'noun' },
    { lemma: 'こんしゅう', reading: 'こんしゅう', romaji: 'konshuu', gloss: 'this week', pos: 'noun' },
  ],
  months: [
    { lemma: 'いちがつ', reading: 'いちがつ', romaji: 'ichigatsu', gloss: 'January', pos: 'noun' },
    { lemma: 'にがつ', reading: 'にがつ', romaji: 'nigatsu', gloss: 'February', pos: 'noun' },
    { lemma: 'さんがつ', reading: 'さんがつ', romaji: 'sangatsu', gloss: 'March', pos: 'noun' },
    { lemma: 'しがつ', reading: 'しがつ', romaji: 'shigatsu', gloss: 'April', pos: 'noun' },
    { lemma: 'ごがつ', reading: 'ごがつ', romaji: 'gogatsu', gloss: 'May', pos: 'noun' },
    { lemma: 'ろくがつ', reading: 'ろくがつ', romaji: 'rokugatsu', gloss: 'June', pos: 'noun' },
    { lemma: 'しちがつ', reading: 'しちがつ', romaji: 'shichigatsu', gloss: 'July', pos: 'noun' },
    { lemma: 'はちがつ', reading: 'はちがつ', romaji: 'hachigatsu', gloss: 'August', pos: 'noun' },
    { lemma: 'くがつ', reading: 'くがつ', romaji: 'kugatsu', gloss: 'September', pos: 'noun' },
    { lemma: 'じゅうがつ', reading: 'じゅうがつ', romaji: 'juugatsu', gloss: 'October', pos: 'noun' },
    { lemma: 'せんげつ', reading: 'せんげつ', romaji: 'sengetsu', gloss: 'last month', pos: 'noun' },
    { lemma: 'らいげつ', reading: 'らいげつ', romaji: 'raigetsu', gloss: 'next month', pos: 'noun' },
    { lemma: 'こんげつ', reading: 'こんげつ', romaji: 'kongetsu', gloss: 'this month', pos: 'noun' },
    { lemma: 'まいつき', reading: 'まいつき', romaji: 'maitsuki', gloss: 'every month', pos: 'noun' },
    { lemma: 'まいしゅう', reading: 'まいしゅう', romaji: 'maishuu', gloss: 'every week', pos: 'noun' },
    { lemma: 'まいあさ', reading: 'まいあさ', romaji: 'maiasa', gloss: 'every morning', pos: 'noun' },
  ],
  counters: [
    { lemma: 'ひとつ', reading: 'ひとつ', romaji: 'hitotsu', gloss: 'one thing', pos: 'number' },
    { lemma: 'ふたつ', reading: 'ふたつ', romaji: 'futatsu', gloss: 'two things', pos: 'number' },
    { lemma: 'みっつ', reading: 'みっつ', romaji: 'mittsu', gloss: 'three things', pos: 'number' },
    { lemma: 'よっつ', reading: 'よっつ', romaji: 'yottsu', gloss: 'four things', pos: 'number' },
    { lemma: 'いつつ', reading: 'いつつ', romaji: 'itsutsu', gloss: 'five things', pos: 'number' },
    { lemma: 'むっつ', reading: 'むっつ', romaji: 'muttsu', gloss: 'six things', pos: 'number' },
    { lemma: 'ななつ', reading: 'ななつ', romaji: 'nanatsu', gloss: 'seven things', pos: 'number' },
    { lemma: 'やっつ', reading: 'やっつ', romaji: 'yattsu', gloss: 'eight things', pos: 'number' },
    { lemma: 'ここのつ', reading: 'ここのつ', romaji: 'kokonotsu', gloss: 'nine things', pos: 'number' },
    { lemma: 'とお', reading: 'とお', romaji: 'too', gloss: 'ten things', pos: 'number' },
    { lemma: 'ひとり', reading: 'ひとり', romaji: 'hitori', gloss: 'one person', pos: 'number' },
    { lemma: 'ふたり', reading: 'ふたり', romaji: 'futari', gloss: 'two people', pos: 'number' },
    { lemma: 'はんぶん', reading: 'はんぶん', romaji: 'hanbun', gloss: 'a half', pos: 'noun' },
    { lemma: 'ぜんぶ', reading: 'ぜんぶ', romaji: 'zenbu', gloss: 'all of it', pos: 'noun' },
    { lemma: 'すうじ', reading: 'すうじ', romaji: 'suuji', gloss: 'a numeral', pos: 'noun' },
    { lemma: 'ばんごう', reading: 'ばんごう', romaji: 'bangou', gloss: 'a number', pos: 'noun' },
  ],
  sports: [
    { lemma: 'スポーツ', reading: 'スポーツ', romaji: 'supootsu', gloss: 'sport', pos: 'noun' },
    { lemma: 'やきゅう', reading: 'やきゅう', romaji: 'yakyuu', gloss: 'baseball', pos: 'noun' },
    { lemma: 'サッカー', reading: 'サッカー', romaji: 'sakkaa', gloss: 'football', pos: 'noun' },
    { lemma: 'テニス', reading: 'テニス', romaji: 'tenisu', gloss: 'tennis', pos: 'noun' },
    { lemma: 'すいえい', reading: 'すいえい', romaji: 'suiei', gloss: 'swimming', pos: 'noun' },
    { lemma: 'プール', reading: 'プール', romaji: 'puuru', gloss: 'a swimming pool', pos: 'noun' },
    { lemma: 'しあい', reading: 'しあい', romaji: 'shiai', gloss: 'a match', pos: 'noun' },
    { lemma: 'せんしゅ', reading: 'せんしゅ', romaji: 'senshu', gloss: 'a player', pos: 'noun' },
    { lemma: 'しゅみ', reading: 'しゅみ', romaji: 'shumi', gloss: 'a hobby', pos: 'noun' },
    { lemma: 'つり', reading: 'つり', romaji: 'tsuri', gloss: 'fishing', pos: 'noun' },
    { lemma: 'とざん', reading: 'とざん', romaji: 'tozan', gloss: 'mountain climbing', pos: 'noun' },
    { lemma: 'さんぽ', reading: 'さんぽ', romaji: 'sanpo', gloss: 'a walk', pos: 'noun' },
    { lemma: 'おどり', reading: 'おどり', romaji: 'odori', gloss: 'a dance', pos: 'noun' },
    { lemma: 'ゲーム', reading: 'ゲーム', romaji: 'geemu', gloss: 'a game', pos: 'noun' },
    { lemma: 'かつ', reading: 'かつ', romaji: 'katsu', gloss: 'to win', pos: 'verb' },
    { lemma: 'まける', reading: 'まける', romaji: 'makeru', gloss: 'to lose', pos: 'verb' },
  ],
  media: [
    { lemma: 'おんがく', reading: 'おんがく', romaji: 'ongaku', gloss: 'music', pos: 'noun' },
    { lemma: 'うた', reading: 'うた', romaji: 'uta', gloss: 'a song', pos: 'noun' },
    { lemma: 'ピアノ', reading: 'ピアノ', romaji: 'piano', gloss: 'a piano', pos: 'noun' },
    { lemma: 'ギター', reading: 'ギター', romaji: 'gitaa', gloss: 'a guitar', pos: 'noun' },
    { lemma: 'えいが', reading: 'えいが', romaji: 'eiga', gloss: 'a film', pos: 'noun' },
    { lemma: 'しんぶん', reading: 'しんぶん', romaji: 'shinbun', gloss: 'a newspaper', pos: 'noun' },
    { lemma: 'ざっし', reading: 'ざっし', romaji: 'zasshi', gloss: 'a magazine', pos: 'noun' },
    { lemma: 'ものがたり', reading: 'ものがたり', romaji: 'monogatari', gloss: 'a story', pos: 'noun' },
    { lemma: 'え', reading: 'え', romaji: 'e', gloss: 'a picture', pos: 'noun' },
    { lemma: 'てがみ', reading: 'てがみ', romaji: 'tegami', gloss: 'a letter', pos: 'noun' },
    { lemma: 'はがき', reading: 'はがき', romaji: 'hagaki', gloss: 'a postcard', pos: 'noun' },
    { lemma: 'きじ', reading: 'きじ', romaji: 'kiji', gloss: 'an article', pos: 'noun' },
    { lemma: 'ニュース', reading: 'ニュース', romaji: 'nyuusu', gloss: 'the news', pos: 'noun' },
    { lemma: 'ばんぐみ', reading: 'ばんぐみ', romaji: 'bangumi', gloss: 'a programme', pos: 'noun' },
  ],
  verbs_daily: [
    { lemma: 'たつ', reading: 'たつ', romaji: 'tatsu', gloss: 'to stand', pos: 'verb' },
    { lemma: 'とぶ', reading: 'とぶ', romaji: 'tobu', gloss: 'to fly', pos: 'verb' },
    { lemma: 'のぼる', reading: 'のぼる', romaji: 'noboru', gloss: 'to climb', pos: 'verb' },
    { lemma: 'さがす', reading: 'さがす', romaji: 'sagasu', gloss: 'to search for', pos: 'verb' },
    { lemma: 'みつける', reading: 'みつける', romaji: 'mitsukeru', gloss: 'to find', pos: 'verb' },
    { lemma: 'ひろう', reading: 'ひろう', romaji: 'hirou', gloss: 'to pick up', pos: 'verb' },
    { lemma: 'すてる', reading: 'すてる', romaji: 'suteru', gloss: 'to throw away', pos: 'verb' },
    { lemma: 'おく', reading: 'おく', romaji: 'oku', gloss: 'to put down', pos: 'verb' },
    { lemma: 'もつ', reading: 'もつ', romaji: 'motsu', gloss: 'to hold', pos: 'verb' },
    { lemma: 'はこぶ', reading: 'はこぶ', romaji: 'hakobu', gloss: 'to carry', pos: 'verb' },
    { lemma: 'おす', reading: 'おす', romaji: 'osu', gloss: 'to push', pos: 'verb' },
    { lemma: 'ひく', reading: 'ひく', romaji: 'hiku', gloss: 'to pull', pos: 'verb' },
    { lemma: 'あける', reading: 'あける', romaji: 'akeru', gloss: 'to open', pos: 'verb' },
    { lemma: 'しめる', reading: 'しめる', romaji: 'shimeru', gloss: 'to close', pos: 'verb' },
    { lemma: 'つける', reading: 'つける', romaji: 'tsukeru', gloss: 'to switch on', pos: 'verb' },
    { lemma: 'けす', reading: 'けす', romaji: 'kesu', gloss: 'to switch off', pos: 'verb' },
    { lemma: 'こわす', reading: 'こわす', romaji: 'kowasu', gloss: 'to break', pos: 'verb' },
    { lemma: 'なおす', reading: 'なおす', romaji: 'naosu', gloss: 'to repair', pos: 'verb' },
    { lemma: 'とる', reading: 'とる', romaji: 'toru', gloss: 'to take', pos: 'verb' },
    { lemma: 'わたす', reading: 'わたす', romaji: 'watasu', gloss: 'to hand over', pos: 'verb' },
    { lemma: 'おくる', reading: 'おくる', romaji: 'okuru', gloss: 'to send', pos: 'verb' },
    { lemma: 'うごく', reading: 'うごく', romaji: 'ugoku', gloss: 'to move', pos: 'verb' },
    { lemma: 'とめる', reading: 'とめる', romaji: 'tomeru', gloss: 'to bring to a stop', pos: 'verb' },
  ],
  verbs_mind: [
    { lemma: 'おもう', reading: 'おもう', romaji: 'omou', gloss: 'to think', pos: 'verb' },
    { lemma: 'かんがえる', reading: 'かんがえる', romaji: 'kangaeru', gloss: 'to consider', pos: 'verb' },
    { lemma: 'しんじる', reading: 'しんじる', romaji: 'shinjiru', gloss: 'to believe', pos: 'verb' },
    { lemma: 'わすれる', reading: 'わすれる', romaji: 'wasureru', gloss: 'to forget', pos: 'verb' },
    { lemma: 'おもいだす', reading: 'おもいだす', romaji: 'omoidasu', gloss: 'to recall', pos: 'verb' },
    { lemma: 'きこえる', reading: 'きこえる', romaji: 'kikoeru', gloss: 'to be audible', pos: 'verb' },
    { lemma: 'みえる', reading: 'みえる', romaji: 'mieru', gloss: 'to be visible', pos: 'verb' },
    { lemma: 'こたえる', reading: 'こたえる', romaji: 'kotaeru', gloss: 'to answer', pos: 'verb' },
    { lemma: 'つたえる', reading: 'つたえる', romaji: 'tsutaeru', gloss: 'to convey', pos: 'verb' },
    { lemma: 'よぶ', reading: 'よぶ', romaji: 'yobu', gloss: 'to call out to', pos: 'verb' },
    { lemma: 'さそう', reading: 'さそう', romaji: 'sasou', gloss: 'to invite', pos: 'verb' },
    { lemma: 'あやまる', reading: 'あやまる', romaji: 'ayamaru', gloss: 'to apologise', pos: 'verb' },
    { lemma: 'ほめる', reading: 'ほめる', romaji: 'homeru', gloss: 'to praise', pos: 'verb' },
    { lemma: 'しかる', reading: 'しかる', romaji: 'shikaru', gloss: 'to scold', pos: 'verb' },
    { lemma: 'やくそく', reading: 'やくそく', romaji: 'yakusoku', gloss: 'a promise', pos: 'noun' },
    { lemma: 'そうだん', reading: 'そうだん', romaji: 'soudan', gloss: 'a consultation', pos: 'noun' },
    { lemma: 'せつめい', reading: 'せつめい', romaji: 'setsumei', gloss: 'an explanation', pos: 'noun' },
    { lemma: 'へんじ', reading: 'へんじ', romaji: 'henji', gloss: 'a reply', pos: 'noun' },
    { lemma: 'あいさつ', reading: 'あいさつ', romaji: 'aisatsu', gloss: 'a greeting', pos: 'noun' },
    { lemma: 'うそ', reading: 'うそ', romaji: 'uso', gloss: 'a lie', pos: 'noun' },
    { lemma: 'ほんとう', reading: 'ほんとう', romaji: 'hontou', gloss: 'the truth', pos: 'noun' },
    { lemma: 'いけん', reading: 'いけん', romaji: 'iken', gloss: 'an opinion', pos: 'noun' },
    { lemma: 'りゆう', reading: 'りゆう', romaji: 'riyuu', gloss: 'a reason', pos: 'noun' },
    { lemma: 'もんだい', reading: 'もんだい', romaji: 'mondai', gloss: 'a problem', pos: 'noun' },
  ],
  adjectives: [
    { lemma: 'うつくしい', reading: 'うつくしい', romaji: 'utsukushii', gloss: 'beautiful', pos: 'adjective' },
    { lemma: 'みにくい', reading: 'みにくい', romaji: 'minikui', gloss: 'ugly', pos: 'adjective' },
    { lemma: 'あまい', reading: 'あまい', romaji: 'amai', gloss: 'sweet', pos: 'adjective' },
    { lemma: 'からい', reading: 'からい', romaji: 'karai', gloss: 'spicy', pos: 'adjective' },
    { lemma: 'しょっぱい', reading: 'しょっぱい', romaji: 'shoppai', gloss: 'salty', pos: 'adjective' },
    { lemma: 'にがい', reading: 'にがい', romaji: 'nigai', gloss: 'bitter', pos: 'adjective' },
    { lemma: 'すっぱい', reading: 'すっぱい', romaji: 'suppai', gloss: 'sour', pos: 'adjective' },
    { lemma: 'かたい', reading: 'かたい', romaji: 'katai', gloss: 'hard', pos: 'adjective' },
    { lemma: 'やわらかい', reading: 'やわらかい', romaji: 'yawarakai', gloss: 'soft', pos: 'adjective' },
    { lemma: 'ふかい', reading: 'ふかい', romaji: 'fukai', gloss: 'deep', pos: 'adjective' },
    { lemma: 'あさい', reading: 'あさい', romaji: 'asai', gloss: 'shallow', pos: 'adjective' },
    { lemma: 'ちかい', reading: 'ちかい', romaji: 'chikai', gloss: 'close by', pos: 'adjective' },
    { lemma: 'とおい', reading: 'とおい', romaji: 'tooi', gloss: 'distant', pos: 'adjective' },
    { lemma: 'おおい', reading: 'おおい', romaji: 'ooi', gloss: 'numerous', pos: 'adjective' },
    { lemma: 'すくない', reading: 'すくない', romaji: 'sukunai', gloss: 'scarce', pos: 'adjective' },
    { lemma: 'きたない', reading: 'きたない', romaji: 'kitanai', gloss: 'dirty', pos: 'adjective' },
    { lemma: 'うるさい', reading: 'うるさい', romaji: 'urusai', gloss: 'noisy', pos: 'adjective' },
    { lemma: 'めずらしい', reading: 'めずらしい', romaji: 'mezurashii', gloss: 'rare', pos: 'adjective' },
    { lemma: 'だいじ', reading: 'だいじ', romaji: 'daiji', gloss: 'important', pos: 'adjective' },
    { lemma: 'へん', reading: 'へん', romaji: 'hen', gloss: 'strange', pos: 'adjective' },
    { lemma: 'らく', reading: 'らく', romaji: 'raku', gloss: 'comfortable', pos: 'adjective' },
    { lemma: 'たいへん', reading: 'たいへん', romaji: 'taihen', gloss: 'tough, awful', pos: 'adjective' },
    { lemma: 'じょうぶ', reading: 'じょうぶ', romaji: 'joubu', gloss: 'sturdy', pos: 'adjective' },
    { lemma: 'まるい', reading: 'まるい', romaji: 'marui', gloss: 'round', pos: 'adjective' },
  ],
  adverbs: [
    { lemma: 'いつも', reading: 'いつも', romaji: 'itsumo', gloss: 'always', pos: 'adverb' },
    { lemma: 'よく', reading: 'よく', romaji: 'yoku', gloss: 'often', pos: 'adverb' },
    { lemma: 'たまに', reading: 'たまに', romaji: 'tamani', gloss: 'occasionally', pos: 'adverb' },
    { lemma: 'まだ', reading: 'まだ', romaji: 'mada', gloss: 'still, not yet', pos: 'adverb' },
    { lemma: 'もう', reading: 'もう', romaji: 'mou', gloss: 'already', pos: 'adverb' },
    { lemma: 'すぐ', reading: 'すぐ', romaji: 'sugu', gloss: 'right away', pos: 'adverb' },
    { lemma: 'やっと', reading: 'やっと', romaji: 'yatto', gloss: 'at last', pos: 'adverb' },
    { lemma: 'だんだん', reading: 'だんだん', romaji: 'dandan', gloss: 'gradually', pos: 'adverb' },
    { lemma: 'もっと', reading: 'もっと', romaji: 'motto', gloss: 'more', pos: 'adverb' },
    { lemma: 'いちばん', reading: 'いちばん', romaji: 'ichiban', gloss: 'most of all', pos: 'adverb' },
    { lemma: 'あまり', reading: 'あまり', romaji: 'amari', gloss: 'not much', pos: 'adverb' },
    { lemma: 'ちょっと', reading: 'ちょっと', romaji: 'chotto', gloss: 'a bit', pos: 'adverb' },
    { lemma: 'はやく', reading: 'はやく', romaji: 'hayaku', gloss: 'quickly', pos: 'adverb' },
    { lemma: 'ゆっくり', reading: 'ゆっくり', romaji: 'yukkuri', gloss: 'slowly', pos: 'adverb' },
    { lemma: 'きっぱり', reading: 'きっぱり', romaji: 'kippari', gloss: 'flatly', pos: 'adverb' },
    { lemma: 'ほとんど', reading: 'ほとんど', romaji: 'hotondo', gloss: 'almost all', pos: 'adverb' },
    { lemma: 'たぶん', reading: 'たぶん', romaji: 'tabun', gloss: 'probably', pos: 'adverb' },
    { lemma: 'また', reading: 'また', romaji: 'mata', gloss: 'again', pos: 'adverb' },
    { lemma: 'まず', reading: 'まず', romaji: 'mazu', gloss: 'first of all', pos: 'adverb' },
    { lemma: 'しかし', reading: 'しかし', romaji: 'shikashi', gloss: 'however', pos: 'expression' },
  ],
  questions: [
    { lemma: 'なに', reading: 'なに', romaji: 'nani', gloss: 'what', pos: 'expression' },
    { lemma: 'だれ', reading: 'だれ', romaji: 'dare', gloss: 'who', pos: 'expression' },
    { lemma: 'どこ', reading: 'どこ', romaji: 'doko', gloss: 'where', pos: 'expression' },
    { lemma: 'いつ', reading: 'いつ', romaji: 'itsu', gloss: 'when', pos: 'expression' },
    { lemma: 'なぜ', reading: 'なぜ', romaji: 'naze', gloss: 'why', pos: 'expression' },
    { lemma: 'どう', reading: 'どう', romaji: 'dou', gloss: 'how', pos: 'expression' },
    { lemma: 'どの', reading: 'どの', romaji: 'dono', gloss: 'which', pos: 'expression' },
    { lemma: 'どれ', reading: 'どれ', romaji: 'dore', gloss: 'which one', pos: 'expression' },
    { lemma: 'どちら', reading: 'どちら', romaji: 'dochira', gloss: 'which of two', pos: 'expression' },
    { lemma: 'どんな', reading: 'どんな', romaji: 'donna', gloss: 'what kind of', pos: 'expression' },
    { lemma: 'だれか', reading: 'だれか', romaji: 'dareka', gloss: 'someone', pos: 'expression' },
    { lemma: 'なにか', reading: 'なにか', romaji: 'nanika', gloss: 'something', pos: 'expression' },
    { lemma: 'どこか', reading: 'どこか', romaji: 'dokoka', gloss: 'somewhere', pos: 'expression' },
    { lemma: 'ぜひ', reading: 'ぜひ', romaji: 'zehi', gloss: 'by all means', pos: 'adverb' },
  ],
  greetings: [
    { lemma: 'ありがとう', reading: 'ありがとう', romaji: 'arigatou', gloss: 'thank you', pos: 'expression' },
    { lemma: 'ください', reading: 'ください', romaji: 'kudasai', gloss: 'please give me', pos: 'expression' },
    { lemma: 'おねがい', reading: 'おねがい', romaji: 'onegai', gloss: 'a request', pos: 'noun' },
    { lemma: 'だいじょうぶ', reading: 'だいじょうぶ', romaji: 'daijoubu', gloss: 'all right', pos: 'adjective' },
    { lemma: 'もしもし', reading: 'もしもし', romaji: 'moshimoshi', gloss: 'hello (on the phone)', pos: 'expression' },
    { lemma: 'いらっしゃい', reading: 'いらっしゃい', romaji: 'irasshai', gloss: 'welcome', pos: 'expression' },
    { lemma: 'ごめん', reading: 'ごめん', romaji: 'gomen', gloss: 'sorry', pos: 'expression' },
    { lemma: 'おめでとう', reading: 'おめでとう', romaji: 'omedetou', gloss: 'congratulations', pos: 'expression' },
    { lemma: 'いってきます', reading: 'いってきます', romaji: 'ittekimasu', gloss: 'I am off', pos: 'expression' },
    { lemma: 'おかえり', reading: 'おかえり', romaji: 'okaeri', gloss: 'welcome back', pos: 'expression' },
    { lemma: 'いただきます', reading: 'いただきます', romaji: 'itadakimasu', gloss: 'said before eating', pos: 'expression' },
    { lemma: 'ごちそうさま', reading: 'ごちそうさま', romaji: 'gochisousama', gloss: 'said after eating', pos: 'expression' },
    { lemma: 'おつかれさま', reading: 'おつかれさま', romaji: 'otsukaresama', gloss: 'thanks for your work', pos: 'expression' },
    { lemma: 'しつれいします', reading: 'しつれいします', romaji: 'shitsureishimasu', gloss: 'excuse me (on leaving)', pos: 'expression' },
  ],
};

export const VOCAB_N5_UNIT = 'vocab-n5';

/**
 * One lesson per theme, in the order a learner meets the subjects rather than
 * alphabetically — food and animals before abstractions like opinions and
 * reasons, and the politeness set last because it is the one that needs the
 * rest to be worth saying.
 *
 * Groups run from 12 to 24 words. Kept uneven on purpose: padding a theme to a
 * round number means adding words nobody needs, and truncating one means
 * dropping a word that belongs.
 */
export const VOCAB_N5_LESSONS: VocabLessonSeed[] = [
  { order: 0, title: 'Words: fruit', groups: ['fruit'], exerciseTypes: ['multipleChoice'] },
  { order: 1, title: 'Words: vegetables', groups: ['vegetables'], exerciseTypes: ['multipleChoice'] },
  { order: 2, title: 'Words: dishes and seasoning', groups: ['dishes'], exerciseTypes: ['multipleChoice'] },
  { order: 3, title: 'Words: the kitchen', groups: ['kitchen'], exerciseTypes: ['multipleChoice'] },
  { order: 4, title: 'Words: animals', groups: ['animals'], exerciseTypes: ['multipleChoice'] },
  { order: 5, title: 'Words: the natural world', groups: ['nature'], exerciseTypes: ['multipleChoice'] },
  { order: 6, title: 'Words: more of the body', groups: ['body'], exerciseTypes: ['multipleChoice'] },
  { order: 7, title: 'Words: health and illness', groups: ['health'], exerciseTypes: ['multipleChoice'] },
  { order: 8, title: 'Words: the wider family', groups: ['family'], exerciseTypes: ['multipleChoice'] },
  { order: 9, title: 'Words: feelings', groups: ['feelings'], exerciseTypes: ['multipleChoice'] },
  { order: 10, title: 'Words: describing people', groups: ['character'], exerciseTypes: ['multipleChoice'] },
  { order: 11, title: 'Words: colours', groups: ['colours'], exerciseTypes: ['multipleChoice'] },
  { order: 12, title: 'Words: more of the house', groups: ['house'], exerciseTypes: ['multipleChoice'] },
  { order: 13, title: 'Words: things you own', groups: ['objects'], exerciseTypes: ['multipleChoice'] },
  { order: 14, title: 'Words: wearing things', groups: ['clothes'], exerciseTypes: ['multipleChoice'] },
  { order: 15, title: 'Words: shops and streets', groups: ['town'], exerciseTypes: ['multipleChoice'] },
  { order: 16, title: 'Words: directions and travel', groups: ['transport'], exerciseTypes: ['multipleChoice'] },
  { order: 17, title: 'Words: going away', groups: ['travel'], exerciseTypes: ['multipleChoice'] },
  { order: 18, title: 'Words: studying', groups: ['school'], exerciseTypes: ['multipleChoice'] },
  { order: 19, title: 'Words: at work', groups: ['work'], exerciseTypes: ['multipleChoice'] },
  { order: 20, title: 'Words: money and shopping', groups: ['money'], exerciseTypes: ['multipleChoice'] },
  { order: 21, title: 'Words: days and weeks', groups: ['days'], exerciseTypes: ['multipleChoice'] },
  { order: 22, title: 'Words: months of the year', groups: ['months'], exerciseTypes: ['multipleChoice'] },
  { order: 23, title: 'Words: counting things', groups: ['counters'], exerciseTypes: ['multipleChoice'] },
  { order: 24, title: 'Words: sport and hobbies', groups: ['sports'], exerciseTypes: ['multipleChoice'] },
  { order: 25, title: 'Words: music, film and print', groups: ['media'], exerciseTypes: ['multipleChoice'] },
  { order: 26, title: 'Words: everyday actions', groups: ['verbs_daily'], exerciseTypes: ['multipleChoice'] },
  { order: 27, title: 'Words: thinking and saying', groups: ['verbs_mind'], exerciseTypes: ['multipleChoice'] },
  { order: 28, title: 'Words: more descriptions', groups: ['adjectives'], exerciseTypes: ['multipleChoice'] },
  { order: 29, title: 'Words: how and how often', groups: ['adverbs'], exerciseTypes: ['multipleChoice'] },
  { order: 30, title: 'Words: asking questions', groups: ['questions'], exerciseTypes: ['multipleChoice'] },
  { order: 31, title: 'Words: everyday politeness', groups: ['greetings'], exerciseTypes: ['multipleChoice'] },
];
