import { Link } from '@tanstack/react-router';

import { Icon } from '../ui/Icon';
import { FlashcardTabs } from './FlashcardTabs';

import './flashcards.css';

export function SharedDecks() {
  return <div className="page flashcard-reference"><FlashcardTabs active="shared" /><header className="flashcard-page-header"><div><p className="flashcard-kicker">COMMUNITY CATALOG</p><h1>Shared Decks</h1><p>A dedicated place for public decks, ready for a real catalog when one exists.</p></div></header><div className="flashcard-shared-layout"><main><section className="flashcard-shared-unavailable glass"><span className="flashcard-status-pill"><i /> Service boundary</span><Icon name="users" size={48} /><h2>Community decks are not available</h2><p>This app does not currently expose a deck-sharing API, public catalog, creator profiles, ratings, moderation state, or download records. Rather than filling this page with sample community content, it stays explicitly empty.</p><div><Link className="btn btn-primary" to="/flashcards-my-decks"><Icon name="layers" size={15} /> Open My Decks</Link><Link className="btn btn-secondary" to="/flashcards-create"><Icon name="pen-square" size={15} /> Create a local deck</Link></div></section><section className="flashcard-shared-requirements glass"><div className="flashcard-section-head"><div><p className="flashcard-kicker">WHAT A REAL CATALOG NEEDS</p><h2>Trustworthy community infrastructure</h2></div></div><div><article><Icon name="layers" size={22} /><h3>Persistent deck records</h3><p>Server-backed cards, versions, owners, and stable identifiers.</p></article><article><Icon name="shield-check" size={22} /><h3>Moderation and attribution</h3><p>Creator identity, reporting, provenance, and content status.</p></article><article><Icon name="download" size={22} /><h3>Safe import semantics</h3><p>A defined copy or subscribe model without silently altering schedules.</p></article></div></section></main><aside className="flashcard-shared-rail"><section className="flashcard-rail-card glass"><p className="flashcard-kicker">AVAILABLE NOW</p><h2>Real learning sources</h2><ul><li><Icon name="check" size={14} /> Course-backed Kana, Vocabulary, Kanji, and Grammar</li><li><Icon name="check" size={14} /> Saved Reading and Dictionary vocabulary</li><li><Icon name="check" size={14} /> Corrections from Writing</li><li><Icon name="check" size={14} /> Browser-local custom decks</li></ul><Link to="/flashcards">Browse available decks <Icon name="chevron-right" size={13} /></Link></section><section className="flashcard-rail-card glass"><p className="flashcard-kicker">PRIVACY</p><h2>Your local decks stay local</h2><p>Nothing created in My Decks is uploaded or made public. A local deck cannot appear here accidentally.</p></section></aside></div></div>;
}
