import { GeneratedQuestion, PromptKind } from '../../dto/exercise-response.dto';

export interface Choice {
  id: string;
  prompt: string;
  answer: string;
  hint?: string;
  audioKey?: string;
  tokens?: string[];
}

export interface QuestionStyle {
  promptKind: PromptKind;
  question: (choice: Choice) => string;
  pool: (unit: string) => Promise<Choice[]>;
}

export interface ExerciseContext {
  lessonId: string;
  userId: string;
  attempt: number;
  index: number;
  random: () => number;
}

export interface GradeInput {
  optionId?: string;
  text?: string;
  selectedTokens?: string[];
}

export interface GradeOutput {
  correct: boolean;
  selectedValue: string;
  correctValue: string;
}

/**
 * Strategy interface for exercise generation and grading (Phase 2 plugin architecture).
 * Decouples ExerciseService from hardcoded question generation logic.
 */
export interface ExercisePlugin {
  /** Unique exercise type key, e.g. 'multipleChoice', 'wordReading', 'listening', 'sentenceBuilding', 'fillInTheBlank', 'flashcard'. */
  readonly exerciseType: string;

  /** Generates a specific question for an item using this exercise strategy. */
  generateQuestion(
    correct: Choice,
    lessonPool: Choice[],
    unitPool: Choice[],
    style: QuestionStyle,
    context: ExerciseContext,
  ): GeneratedQuestion;

  /** Grades a submitted answer for a question generated by this plugin. */
  gradeAnswer(question: GeneratedQuestion, input: GradeInput): GradeOutput;
}
